### ISSUE TITLE
Unable to set the start date older than +3 

### ISSUE THREAD

**Issue by pavan2004it** [aws-samples/aws-cost-explorer-report#23]
I am getting the below error 

<' not supported between instances of 'str' and 'float': TypeError
Traceback (most recent call last):
  File "/var/task/lambda.py", line 528, in main_handler
    Style='Total', IncSupport=True)
  File "/var/task/lambda.py", line 435, in addReportservice
    df = df.sort_values(sort, ascending=False)
  File "/var/task/./vendored/pandas/core/frame.py", line 5014, in sort_values
    k, kind=kind, ascending=ascending, na_position=na_position
  File "/var/task/./vendored/pandas/core/sorting.py", line 260, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '<' not supported between instances of 'str' and 'float'

I am setting the start date to 

self.start = (datetime.date.today() - relativedelta(months=+4)).replace(day=1)

if i make it +3 the report gets generated , wanted to know how to fix the error

**Comment by pavan2004it** [comment]
issue resolved closing this ... the data was null hence was getting the error message,,
